# Generated by Django 5.1 on 2026-07-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('memory', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('promo_price', models.CharField(blank=True, max_length=100, null=True)),
                ('photos', models.JSONField(blank=True, null=True)),
                ('product_code', models.CharField(blank=True, max_length=100, null=True)),
                ('reviews_count', models.CharField(blank=True, max_length=50, null=True)),
                ('diagonal', models.CharField(blank=True, max_length=100, null=True)),
                ('display_resolution', models.CharField(blank=True, max_length=100, null=True)),
                ('specifications', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
